### ISSUE TITLE
Add mentions in ICQ

### ISSUE THREAD

**Issue by saint88** [go-icq/icq#1]
Please add mentions supported in icq messages.

Fix:
func (a *API) SendMessage(to string, message string, **mentions []string**) (*MessageResponse, error) {
	a.mu.Lock()
	defer a.mu.Unlock()
	v := url.Values{
		"aimsid":   []string{a.token},
		"r":        []string{strconv.FormatInt(time.Now().Unix(), 10)},
		"t":        []string{to},
		"message":  []string{message},
		**"mentions": []string{strings.Join(mentions, ",")},**
	}
	req, err := http.NewRequest(http.MethodGet, a.baseUrl+"/im/sendIM?"+v.Encode(), nil)
	if err != nil {
		return nil, err
	}
	resp, err := a.client.Do(req)
	if err != nil {
		return nil, err
	}

**Comment by neonxp** [comment]
Привет! Сделал версию 2, т.к. изменился контракт. Сделал немного не так, как ты предложил - посмотри в примере. Параметры передаются теперь через структуру, чтобы не было необходимости перечислять все параметры. `Mentions []string` теперь внутри структуры `icq.Message`
